# -*- coding: utf-8 -*-
"""load_predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S9Dn38ZAsUCRXjFctvYHVnCKBtWKstNi

### **load_predict.py file that loads a pre-trained model and uses it to predict the category of a new reviews against anti descrimination**

*Done by Paramesh E*
"""

# Connecting drive
from google.colab import drive
drive.mount('/content/drive/')

import joblib
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# loading the saved model from file
mnb_model = joblib.load('/content/drive/MyDrive/Colab Notebooks/mnb_model_ad.pkl')

# loading the saved Vectorizer from file
count_vect = joblib.load('/content/drive/MyDrive/Colab Notebooks/Vectorizer_ad.pkl')

# loading the review text that you want to predict the category for
review_text = "@AmericanAir inconsistent and rude staff. Randomly pulling people to check luggage vs allowing to put in overhead bins. — Lauren Castillon (@lam3185) October 23, 2014" #live review

# transforming the review text using the fitted CountVectorizer object
X_review = count_vect.transform([review_text])

# using the trained model to predict the category of the review
predicted_category = mnb_model.predict(X_review)

# predictions
print("Predicted category:", predicted_category)